Reworking to deal with sources where a track starts really late in the file

diff --git a/qsvAv1 b/qsvAv1
--- a/qsvAv1
+++ b/qsvAv1
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Debug output
-#set -ex
+set -ex
 
 ###########################
 # Assumes jellyfin-ffmpeg is installed and symlinked in /usr/bin.
@@ -70,16 +70,17 @@ for chapter in $STARTSTOP ; do
         startTime=$(jq .chapters[$begin].start_time "$WIP/chapters.json" | sed 's/\"//g')
         endTime=$(jq .chapters[$end].end_time "$WIP/chapters.json" | sed 's/\"//g')
         ffmpeg \
-                -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -y -hide_banner -stats -fflags genpts -loglevel error \
+                -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -y -hide_banner -stats -loglevel error \
                 -init_hw_device qsv=qs@va \
                 -filter_hw_device qs \
                 -hwaccel qsv \
                 -hwaccel_output_format qsv \
-                -i "$INPUTFILE" \
+		-fflags +genpts+igndts \
                 $INPUT_LIST \
+		-avoid_negative_ts make_zero -max_interleave_delta 0 \
                 -ss $startTime \
                 -to $endTime \
-                -map_chapters 0 \
+                -map_chapters 2 \
                 $MAPPING \
                 -c:v av1_qsv \
                 -preset veryslow \
@@ -88,11 +89,13 @@ for chapter in $STARTSTOP ; do
                 -c:s copy \
 		-disposition:s 0 \
                 -global_quality:v 26 \
-                -look_ahead 1 \
+		-low_delay_brc 1 -extbrc 1 \
                 -look_ahead_depth 100 \
+		-max_muxing_queue_size 2048 \
                 "$outputFile"
 done
 }
+                #-i "$INPUTFILE" \
 
 # During FOSS audio conversion, audio tracks are extracted and need to be re-muxed for easier insertion into the final video
 buildAudioMapping () {
@@ -214,7 +217,7 @@ generateFilters () {
 	esac
 
 	# ffmpeg to detect black bars for cropping.
-	rawCrop=$(ffmpeg -ss 250 -to 260 -i "$INPUTFILE" -vf cropdetect=mode=black,metadata=mode=print -f null - 2>&1 | awk '/crop=/ {a=$NF} END{print a}' | awk -F '=' '{print $2}')
+	rawCrop=$(ffmpeg -ss 30 -to 40 -i "$INPUTFILE" -vf cropdetect=mode=black,metadata=mode=print -f null - 2>&1 | awk '/crop=/ {a=$NF} END{print a}' | awk -F '=' '{print $2}')
 
 	w=$(echo $rawCrop | awk -F ":" '{print $1}')
 	h=$(echo $rawCrop | awk -F ":" '{print $2}')
@@ -250,8 +253,14 @@ processParallelTasks () {
 
 # Only performs language selection
 processAudioSubs () {
-	echo "ffmpeg -hide_banner -loglevel error -stats -y -i \"$INPUTFILE\" -sn -c:v copy -c:a copy $LANG_OPTIONS \"$WIP/audio.mka\"" >> "$PARALLEL"
-	echo "ffmpeg -hide_banner -loglevel error -stats -y -i \"$INPUTFILE\" -an -map 0:v -c:v copy -c:s copy $LANG_OPTIONS \"$WIP/subtitles.mkv\"" >> "$PARALLEL"
+	echo "ffmpeg -hide_banner -loglevel error -stats -y -fflags +genpts+igndts -i \"$INPUTFILE\" -sn -c:v copy -c:a copy $LANG_OPTIONS -avoid_negative_ts make_zero -max_interleave_delta 0 -max_muxing_queue_size 2048 \"$WIP/audio.mka\"" >> "$PARALLEL"
+	echo "ffmpeg -hide_banner -loglevel error -stats -y -fflags +genpts+igndts -i \"$INPUTFILE\" -an -map 0:v -c:v copy -c:s copy -map 0:t? -map_chapters 0 $LANG_OPTIONS -avoid_negative_ts make_zero -max_interleave_delta 0 -max_muxing_queue_size 2048 \"$WIP/subtitles.mkv\"" >> "$PARALLEL"
+}
+
+# Extracts video into separate file
+extractVideo () {
+	echo "Extracting video track"
+	echo "ffmpeg -hide_banner -loglevel error -stats -fflags +genpts+igndts -y -i \"$INPUTFILE\" -an -sn -c:v copy -avoid_negative_ts make_zero -max_interleave_delta 0 -max_muxing_queue_size 2048 \"$WIP/video.mp4\"" >> $PARALLEL
 }
 
 # Creates lanuage English selection parameters for audio and subtitles.  If ANIME option is enabled, also selects Japanese tracks.
@@ -302,8 +311,9 @@ if [ $DV -eq 1 ]; then
         echo "Generating final input list and mappings."
 else
         echo "Generating final input list and mappings."
-        INPUT_LIST="-i $WIP/audio.mka -i $WIP/subtitles.mkv"
-        MAPPING="-map 0:v -map 1:a -map 2:s? -map 0:t?"
+        #INPUT_LIST="-i $WIP/audio.mka -i $WIP/subtitles.mkv"
+        INPUT_LIST="-i $WIP/video.mp4 -i $WIP/audio.mka -i $WIP/subtitles.mkv"
+        MAPPING="-map 0:v -map 1:a -map 2:s? -map 2:t?"
 fi
 
 # If the -f 1 option is used, all audio tracks will be converted to FOSS audio codecs
@@ -317,6 +327,7 @@ if [ $FOSS -eq 1 ]; then
 else
 	echo "Performing audio/sub language selection."
         processAudioSubs
+	extractVideo
 	processParallelTasks
 fi
 
