Additional filter tweaking, adding exit codes to aid in recursive loops when using this script

diff --git a/qsvAv1Beta b/qsvAv1Beta
--- a/qsvAv1Beta
+++ b/qsvAv1Beta
@@ -28,6 +28,7 @@ ENGLISHSELECTION=0
 AUDIOCONVERSION=0
 EMPTYCHAPTERPROBE=""
 FRAMERATE=""
+EXITCODE=0
 
 # Reads input paramamters
 while getopts i:c:a:k:r:s:h:w:e:o:m: option; do
@@ -59,6 +60,21 @@ fi
 
 WIP=${SCRATCHDIR}/WIP
 mkdir -p ${WIP}
+
+checkExitCode () {
+	function=$1
+	if [ $EXITCODE -eq -1 ]; then
+		echo "Encode completed successfully."
+		# WIP cleanup
+		echo "Cleaning up WIP files/folders"
+		rm -f "${remuxOutputFile}"
+		rm -rf ${WIP}
+		exit 0
+	elif [ $EXITCODE -ne 0 ]; then
+		echo "FFmpeg returned a non-zero exit code in ${function}.  Leaving WIP files in place and quitting."
+		exit 1
+	fi
+}
 
 # Uses Intel QSV to encode the original AV1.  Maps the audio tracks for the selected languages, and converts to them to OPUS.
 # Includes attachments if present.  If splitting out episodes from a MKV that came off the disc as a single file, it will loop through for each episode.
@@ -113,7 +129,9 @@ while read file; do
 		-max_muxing_queue_size 2048 \
 		-max_interleave_delta 0 \
 		-avoid_negative_ts disabled \
-                "${outputFile}" < /dev/null
+                "${outputFile}" < /dev/null 2>&1 > /dev/null
+	EXITCODE=$?
+	checkExitCode "av1Encode"
 done <<< "${CHAPTERFILES}"
 
 # Rechecks chapters, but only if present in input file
@@ -167,7 +185,9 @@ while read file; do
                 -max_muxing_queue_size 2048 \
                 -max_interleave_delta 0 \
                 -avoid_negative_ts disabled \
-                "${outputFile}" < /dev/null
+                "${outputFile}" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+	checkExitCode "remuxOnly"
 done <<< "${CHAPTERFILES}"
 
 # Rechecks chapters, but only if present in input file
@@ -220,7 +240,9 @@ while read file; do
                 -max_muxing_queue_size 2048 \
                 -max_interleave_delta 0 \
                 -avoid_negative_ts disabled \
-                "${outputFile}" < /dev/null
+                "${outputFile}" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+	checkExitCode "audioConversionOnly"
 done <<< "${CHAPTERFILES}"
 
 # Rechecks chapters, but only if present in input file
@@ -544,7 +566,8 @@ splitEpisodes () {
 		echo "Writing file for chapters ${first} thru ${last}"
 
 		ffmpeg -v error -stats -y -fflags +genpts+igndts -i "${remuxOutputFile}" -map 0 -codec copy ${chapterTimestamp} -max_muxing_queue_size 2048 -max_interleave_delta 0 -avoid_negative_ts disabled "${segmentFile}" < /dev/null
-
+		EXITCODE=$?
+		checkExitCode "splitEpisodes $first $last"
 	        i=$(echo $((${i} + ${CHAPTERSEPISODE})) | bc)
 	done
 	CHAPTERFILES=$(ls ${WIP})
@@ -578,6 +601,8 @@ chapterSelect () {
 	echo "Writing file for chapters ${startChapter} thru ${endChapter}"
                 
         ffmpeg -v error -stats -y -fflags +genpts+igndts -i "${remuxOutputFile}" -map 0 -codec copy ${chapterTimestamp} -max_muxing_queue_size 2048 -max_interleave_delta 0 -avoid_negative_ts disabled "${segmentFile}" < /dev/null
+	EXITCODE=$?
+	checkExitCode "ChapterSelect $startChapter $endChapter"
 }
 
 progressiveInInterlaced () {
@@ -588,9 +613,13 @@ progressiveInInterlaced () {
 	pixFmt=$5
 
 	echo "Splitting raw video by field then rejoining"
-	ffmpeg -v error -y -stats -i "${videoToSplit}" -filter_complex "[0]il=l=d:c=d,split[o][e];[o]crop=iw:ih/2:0:0[odd];[e]crop=iw:ih/2:0:ih/2[even];[odd][even]vstack,il=l=i:c=i" -video_size ${width}x${height} -pixel_format ${pixFmt} -framerate ${frameRate} -f rawvideo "${WIP}/rejoined.yuv" < /dev/null
+	ffmpeg -v error -y -stats -i "${videoToSplit}" -filter_complex "[0]il=l=d:c=d,split[o][e];[o]crop=iw:ih/2:0:0[odd];[e]crop=iw:ih/2:0:ih/2[even];[odd][even]vstack,il=l=i:c=i" -video_size ${width}x${height} -pixel_format ${pixFmt} -framerate ${frameRate} -f rawvideo "${WIP}/rejoined.yuv" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+        checkExitCode "progressiveInInterlaced"
 	echo "Muxing rejoined raw video with original audio, subtitles, attachments, and metadata"
-	ffmpeg -v error -y -stats -video_size ${width}x${height} -pixel_format ${pixFmt} -framerate ${frameRate} -i "${WIP}/rejoined.yuv" -i "${videoToSplit}" -map 0:v -map 1:a -map 1:s? -map 1:t? -map_metadata 1 -map_chapters 1 -codec copy -max_muxing_queue_size 2048 -max_interleave_delta 0 -avoid_negative_ts disabled "${WIP}/finalRejoinedVideo.mkv" < /dev/null
+	ffmpeg -v error -y -stats -video_size ${width}x${height} -pixel_format ${pixFmt} -framerate ${frameRate} -i "${WIP}/rejoined.yuv" -i "${videoToSplit}" -map 0:v -map 1:a -map 1:s? -map 1:t? -map_metadata 1 -map_chapters 1 -codec copy -max_muxing_queue_size 2048 -max_interleave_delta 0 -avoid_negative_ts disabled "${WIP}/finalRejoinedVideo.mkv" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+        checkExitCode "progressiveInInterlaced"
 	echo "Replacing WIP file with new file"
 	mv "${WIP}/finalRejoinedVideo.mkv" "${videoToSplit}"
 }
@@ -601,11 +630,21 @@ generateFilters () {
 		sar="setsar=1:1,"
 	else 
 		sar=""
-	fi   
-	if [ ${setDetelecine} -eq 1 ]; then 
-		detelecine="hwdownload,format=${inputFormat},crop=w=${w}:h=${h}:x=${x}:y=${y},pullup,dejudder,fps=${frameRate},hwupload,"
+	fi
+	if [ ${setHWDL} -eq 1 ]; then
+		hwDownload="hwdownload,"
 	else
-		detelecine="hwdownload,format=${inputFormat},crop=w=${w}:h=${h}:x=${x}:y=${y},hwupload"
+		hwDownload=""
+	fi
+	if [ ${setHWUL} -eq 1 ]; then
+		hwUpload="hwupload,"
+	else
+		hwupLoad=""
+	fi
+	if [ ${setDetelecine} -eq 1 ]; then 
+		detelecine="format=${inputFormat},crop=w=${w}:h=${h}:x=${x}:y=${y},pullup,dejudder,fps=${frameRate},"
+	else
+		detelecine="format=${inputFormat},crop=w=${w}:h=${h}:x=${x}:y=${y},"
 	fi   
 	if [ ${setDeinterlace} -eq 1 ]; then 
 		deinterlace="vpp_qsv=rate=1:deinterlace=2:scale_mode=5"
@@ -623,9 +662,10 @@ generateFilters () {
 		scale="format=p010le"
 	fi
 	if [ ${setDetelecine} -eq 0 ] && [ ${setDeinterlace} -eq 0 ]; then
-		echo "vpp_qsv=cw=${w}:ch=${h}:cx=${x}:cy=${y}:scale_mode=5,${sar}format=p010le"
+		#echo "format=${inputFormat},${hwUpload}vpp_qsv=cw=${w}:ch=${h}:cx=${x}:cy=${y},${sar}${scale}"
+		echo "format=${inputFormat},vpp_qsv=cw=${w}:ch=${h}:cx=${x}:cy=${y},${sar}${scale}"
 	else
-		echo "${detelecine}${deinterlace}${newFrameRate},${sar}${scale}"
+		echo "${hwDownload}${detelecine}${hwUpload}${deinterlace}${newFrameRate},${sar}${scale}"
 	fi
 }
 
@@ -649,6 +689,7 @@ generateFilterParameters () {
 	setSar=0
 	setScale=0
 	setFramerate=0
+	setHWUL=0
 
 	# Checks for various interface types.  Uses QSV "advanced" de-interlace option if interlaced.
 	case ${interlaced} in
@@ -703,7 +744,48 @@ generateFilterParameters () {
 		inputFormat="nv12"
 	fi
 
+        # If SAR is not 1:1, will set to 1:1 and dynamically scale the video accordingly.
+        echo "Automatically detecting SAR/DAR"
+        if [[ "${sar}" != "1:1" ]] && [ ! -z ${sar} ]; then
+                setSar=1
+                sarNum=$(echo ${sar} | awk -F ':' '{print $1}')
+                sarDenom=$(echo ${sar} | awk -F ':' '{print $2}')
+                sarRatio=$(awk "BEGIN {print ${sarNum} / ${sarDenom}}")
+                darNum=$(echo ${dar} | awk -F ':' '{print $1}')
+                darDenom=$(echo ${dar} | awk -F ':' '{print $2}')
+                darRatio=$(awk "BEGIN {print ${darNum} / ${darDenom}}")
+                darRatioWS=$(awk "BEGIN {print 16 /9}")
+                darRatioDiff=$(awk "BEGIN {print ${darRatio} - ${darRatioWS}}")
+                darRatioDiff=${darRatioDiff#-}
+                ratio=$(awk "BEGIN {print ${darRatio} * ${sarRatio}}")
+                ratioDiff=$(awk "BEGIN {print ${ratio} - 1.333}")
+                ratioDiff=${ratioDiff#-}
+                if [[ $(awk "BEGIN{print (${ratioDiff} < 0.2)}") -eq 1 ]]; then
+                        echo "Altering dimensions to fix aspect ratio to ~4/3"
+                        setScale=1
+                        h_scale=${h}
+                        w_scale=$(printf "%.0f" `awk "BEGIN {print ${height} * 1.333}"`)
+                # Edge case.  Sometimes DAR is set to 16:9 and dynamically calculating via SAR/DAR results in extra wide, stretched, video.
+                elif [[ $(awk "BEGIN{print (${ratioDiff} > 0.2)}") -eq 1 ]] && [[ $(awk "BEGIN{print (${darRatioDiff} < 0.05)}") -eq 1 ]]; then
+                        echo "Altering dimension to fix aspect ratio to ~16/9"
+                        setScale=1
+                        w_scale=${w}
+                        h_scale=$(printf "%.0f" `awk "BEGIN {print ${width} / 1.777777778}"`)
+                else
+                        echo "Altering dimensions to fix aspect ratio, widescreen"
+                        setScale=1
+                        w_scale=${w}
+                        h_scale=$(printf "%.0f" `awk "BEGIN {print ${width} / ${ratio}}"`)
+                fi
+        elif [ -z ${sar} ]; then
+                echo "SAR not set.  Setting to 1:1"
+                setSar=1
+                w_scale=${w}
+                h_scale=${h}
+        fi
+
 	if [ ${setDeinterlace} -eq 1 ]; then
+		setHWUL=1
 		echo "Detected interlaced video, checking for telecine"
 		if [ "${numOfFrames}" == "" ]; then
 			readFrames=3600
@@ -782,46 +864,6 @@ generateFilterParameters () {
 		FRAMERATE="-fps_mode passthrough"
 	fi
 
-	# If SAR is not 1:1, will set to 1:1 and dynamically scale the video accordingly.
-	echo "Automatically detecting SAR/DAR"
-	if [[ "${sar}" != "1:1" ]] && [ ! -z ${sar} ]; then
-		setSar=1
-		sarNum=$(echo ${sar} | awk -F ':' '{print $1}')
-		sarDenom=$(echo ${sar} | awk -F ':' '{print $2}')
-		sarRatio=$(awk "BEGIN {print ${sarNum} / ${sarDenom}}")
-		darNum=$(echo ${dar} | awk -F ':' '{print $1}')
-		darDenom=$(echo ${dar} | awk -F ':' '{print $2}')
-		darRatio=$(awk "BEGIN {print ${darNum} / ${darDenom}}")
-		darRatioWS=$(awk "BEGIN {print 16 /9}")
-		darRatioDiff=$(awk "BEGIN {print ${darRatio} - ${darRatioWS}}")
-		darRatioDiff=${darRatioDiff#-}
-		ratio=$(awk "BEGIN {print ${darRatio} * ${sarRatio}}")
-		ratioDiff=$(awk "BEGIN {print ${ratio} - 1.333}")
-		ratioDiff=${ratioDiff#-}
-		if [[ $(awk "BEGIN{print (${ratioDiff} < 0.2)}") -eq 1 ]]; then
-			echo "Altering dimensions to fix aspect ratio to ~4/3"
-			setScale=1
-			h_scale=${h}
-               		w_scale=$(printf "%.0f" `awk "BEGIN {print ${height} * 1.333}"`)
-		# Edge case.  Sometimes DAR is set to 16:9 and dynamically calculating via SAR/DAR results in extra wide, stretched, video.
-		elif [[ $(awk "BEGIN{print (${ratioDiff} > 0.2)}") -eq 1 ]] && [[ $(awk "BEGIN{print (${darRatioDiff} < 0.05)}") -eq 1 ]]; then
-			echo "Altering dimension to fix aspect ratio to ~16/9"
-			setScale=1
-			w_scale=${w}
-	                h_scale=$(printf "%.0f" `awk "BEGIN {print ${width} / 1.777777778}"`)
-		else
-			echo "Altering dimensions to fix aspect ratio, widescreen"
-			setScale=1
-			w_scale=${w}
-			h_scale=$(printf "%.0f" `awk "BEGIN {print ${width} / ${ratio}}"`)
-		fi
-	elif [ -z ${sar} ]; then
-		echo "SAR not set.  Setting to 1:1"
-		setSar=1
-		w_scale=${w}
-		h_scale=${h}
-	fi
-
 	FILTERS=$(generateFilters)
 
 	echo "Video filter result: ${FILTERS}"
@@ -835,7 +877,9 @@ convertEIA608 () {
 	mapEIATracks=$(for index in ${eiaTracks}; do
 		echo "-map 0:${index}"
 	done)
-	ffmpeg -v error -stats -y -i "${INPUTFILE}" -vn -an ${mapEIATracks} -c:s srt "${WIP}/${srtMKVFile}"
+	ffmpeg -v error -stats -y -i "${INPUTFILE}" -vn -an ${mapEIATracks} -c:s srt "${WIP}/${srtMKVFile}" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+        echo "$EXITCODE"
 	mapSubTracks=$(if [ -z ${otherSubTracks} ]; then
 			echo "-map 1:s"
 		else
@@ -844,7 +888,9 @@ convertEIA608 () {
 			done
 			echo "-map 1:s"
 		fi)
-	ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -i "${WIP}/${srtMKVFile}" -codec copy -map_chapters 0 -map 0:v -map 0:a? ${mapSubTracks} -map 0:t? "${remuxOutputFile}" < /dev/null
+	ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -i "${WIP}/${srtMKVFile}" -codec copy -map_chapters 0 -map 0:v -map 0:a? ${mapSubTracks} -map 0:t? "${remuxOutputFile}" < /dev/null 2>&1 > /dev/null
+        EXITCODE=$?
+        echo "$EXITCODE"
 	rm -f "${WIP}/${srtMKVFile}"
 }
 
@@ -901,6 +947,63 @@ repairChapters () {
 	        ffmpeg -v error -y -stats -fflags +genpts+igndts -i "${inputFileRepair}" -f ffmetadata -i ${NEWCHAPTERS} -map 0 -codec copy -map_metadata 1 -map_chapters 1 -max_muxing_queue_size 2048 -max_interleave_delta 0 -avoid_negative_ts disabled "${outputFileRepair}" < /dev/null
 		rm $CHAPTERS $NEWCHAPTERS
 	fi
+	EXITCODE=$?
+	checkExitCode "repairChapters"
+}
+
+initialRemux () {
+echo "Remuxing file to re-order tracks"
+if [[ "${ext}" == "avi" ]] || [[ "${ext}" == "mpg" ]] || [[ "${ext}" == "mp4" ]] || [[ "${ext}" == "m2ts" ]] || [ "${NOEIA608}" = 'false' ]; then
+        if [ "${NOMOVTEXT}" = 'false' ] && [ "${NOMSMPEG}" = 'true' ]; then
+                echo "Remuxing to MP4"
+                newExt="mp4"
+                remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
+                if [ ${BADCHAPTER} -gt 1 ]; then
+                        repairChapters "${INPUTFILE}" "${remuxOutputFile}"
+                else
+                        ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
+                fi
+        elif [ "${NOEIA608}" = 'false' ]; then
+                echo "Remuxing to MKV and converting EIA608 subs"
+                newExt="mkv"
+                remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
+                if [ ${BADCHAPTER} -gt 1 ]; then
+                        repairChapters "${INPUTFILE}" "${remuxOutputFile}"
+                        convertEIA608
+                else
+                        convertEIA608
+                fi
+        elif [[ "${ext}" == "m2ts" ]]; then
+                echo "Remuxing to M2TS"
+                newExt="m2ts"
+                remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
+                if [ ${BADCHAPTER} -gt 1 ]; then
+                        repairChapters "${INPUTFILE}" "${remuxOutputFile}"
+                else
+                        ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
+                fi
+        else
+                echo "Remuxing to MKV"
+                newExt="mkv"
+                remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
+                if [ ${BADCHAPTER} -gt 1 ]; then
+                        repairChapters "${INPUTFILE}" "${remuxOutputFile}"
+                else
+                        ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
+                fi
+        fi
+else
+        echo "Remuxing to MKV"
+        newExt="mkv"
+        remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
+        if [ ${BADCHAPTER} -gt 1 ]; then
+                repairChapters "${INPUTFILE}" "${remuxOutputFile}"
+        else
+                ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
+        fi
+fi
+
+EXITCODE=$?
 }
 
 # Remuxes input file so that video tracks are grouped first, audio second, subs, third.  Simplifies track selection logic
@@ -918,57 +1021,8 @@ inputFile=$(echo $INPUTFILE | awk -F '/' '{print $NF}')
 # Checks if end time for last chapter is after the video's duration
 BADCHAPTER=$(checkChapters "${INPUTFILE}")
 
-echo "Remuxing file to re-order tracks"
-if [[ "${ext}" == "avi" ]] || [[ "${ext}" == "mpg" ]] || [[ "${ext}" == "mp4" ]] || [[ "${ext}" == "m2ts" ]] || [ "${NOEIA608}" = 'false' ]; then
-	if [ "${NOMOVTEXT}" = 'false' ] && [ "${NOMSMPEG}" = 'true' ]; then
-		echo "Remuxing to MP4"
-	        newExt="mp4"
-	        remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
-		if [ ${BADCHAPTER} -gt 1 ]; then
-			repairChapters "${INPUTFILE}" "${remuxOutputFile}"
-		else
-			ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
-		fi
-	elif [ "${NOEIA608}" = 'false' ]; then
-		echo "Remuxing to MKV and converting EIA608 subs"
-		newExt="mkv"
-		remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
-                if [ ${BADCHAPTER} -gt 1 ]; then
-			repairChapters "${INPUTFILE}" "${remuxOutputFile}"
-			convertEIA608
-		else
-			convertEIA608
-		fi
-        elif [[ "${ext}" == "m2ts" ]]; then
-		echo "Remuxing to M2TS"
-		newExt="m2ts"
-	        remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
-                if [ ${BADCHAPTER} -gt 1 ]; then
-			repairChapters "${INPUTFILE}" "${remuxOutputFile}"
-                else
-                        ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
-                fi
-	else
-		echo "Remuxing to MKV"
-	        newExt="mkv"
-	        remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
-                if [ ${BADCHAPTER} -gt 1 ]; then
-			repairChapters "${INPUTFILE}" "${remuxOutputFile}"
-                else
-                        ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
-                fi
-	fi
-else
-	echo "Remuxing to MKV"
-	newExt="mkv"
-	remuxOutputFile=$(echo ${SCRATCHDIR}/${inputFile} | sed "s/.${ext}/-remux.${newExt}/g")
-	if [ ${BADCHAPTER} -gt 1 ]; then
-		repairChapters "${INPUTFILE}" "${remuxOutputFile}"
-	else
-		ffmpeg -v error -stats -fflags +genpts+igndts -y -i "${INPUTFILE}" -codec copy -map_chapters 0 -map 0:v? -map 0:a? -map 0:s? -map 0:t? "${remuxOutputFile}"
-	fi
-fi
-
+initialRemux
+checkExitCode "initialRemux"
 
 # Get ffprobe info to be used by other functions.
 AUDIOFFPROBE=$(ffprobe -i "${remuxOutputFile}" -select_streams a -show_entries stream -v quiet -of json)
@@ -1117,7 +1171,6 @@ else
 	av1Encode
 fi
 
-# WIP cleanup
 echo "Cleaning up WIP files/folders"
-rm -f "${remuxOutputFile}"
-rm -rf ${WIP}
+EXITCODE=-1
+checkExitCode "END"
